### ISSUE TITLE
Webster doesn't work

### ISSUE THREAD

**Issue by raffaelemancuso** [mhwgoo/cambridge#3]
```
camb -wf hello
2022-11-14 10:29:27 ERROR webster.py[152] The fetched result is not what we intended for the word due to the network or website reasons, please try again.
```

**Comment by mhwgoo** [comment]
-w -f 
I found the webster website sometimes is unstable, try again now? Let's see the result.

**Comment by mhwgoo** [comment]
It happened before but very rarely. Today I just found all fetches to webster failed and the reason is the merriam webster website has done a whole new update. Therefore its html structure might have changed, so my parsing codes need to alter accordingly. 

Thank you for your feedback.

**Comment by mhwgoo** [comment]
I have finished parsing the updated Webster website. Please update your cambridge version to the newest v3.4.1. Thanks!

**Comment by raffaelemancuso** [comment]
Thanks!

**Comment by raffaelemancuso** [comment]
It works again. Thanks.
