### ISSUE TITLE
Missing empty line for idioms

### ISSUE THREAD

**Issue by Alvinceleste2** [mhwgoo/cambridge#9]
Hi there. I'm currently making a parser for the output of this program to automate the creation of some english vocabulary flashcards. The problem is that the way I've found to guess if the query to the dictionary is OK is by checking the first line of the exit. If it is empty, it means that a definition has been found for a word, if not, it means that the search has failed. The fact is that, when an idiom is being seached, no first empty line is displayed, so my program assumes that the search has failed. I think it may be a little coherence mistake, as every exit for the program starts with that particular first line break. I could provide you more information about how my program works if necessary. Thanks :)

**Comment by Alvinceleste2** [comment]
How to reproduce:
$ camb cat

cat noun [ C ]
uk |kæt| us |kæt|
: a small animal with fur, four legs, a tail, and claws, usually kept as a pet or for catching mice
: any member of the group of animals similar to the cat, such as the lion
|the cat family

SEE ALSO
  • big cat

IDIOMS
  • be the cat's whiskers
  • fight like cat and dog
  • has the cat got your tongue?
  • let the cat out of the bag
  • like a cat on a hot tin roof
  • like the cat that got the cream
  • look like something the cat brought/dragged in
  • not have a cat in hell's chance
  • play cat and mouse
  • put/set the cat among the pigeons
  • while the cat's away, the mice will play

FOUND "cat" from CAMBRIDGE in cache. You can add "-f -w" to fetch the MERRIAM_WEBSTER dictionary

but, if it is an idiom:

$ camb curiosity killed the cat
curiosity killed the cat idiom saying
: said to warn someone not to ask too many questions about something

Pay attention to the line break just after the prompt command. Unless it's an idiom, there's line break. I would need that line break to be also displayed for idioms.

**Comment by mhwgoo** [comment]
Hi, you can update to the latest version v3.13.7 to get your preferred result. However, I'm afraid it's not a very reliable approach to telling if a word exists or not in the dictionary. I recommend you add `-n` or `--nosuggestions` flag to fetch the dictionary by shell command, this way the program will return error number "-1" if the word can not be found; or you can do the fetching by calling `async def search_cambridge(session, input_word, is_fresh=False, is_ch=False, no_suggestions=True, req_url=None)` to have the same effect.

**Comment by Alvinceleste2** [comment]
Thanks! Also, I'm realizing that line break is left for phrases as well. Additionally, phrases do not have ":" before the definitions. That is also important for my program, as I use them to search the definitions properly. Could you please update it?

**Comment by Alvinceleste2** [comment]
Example:

$ camb on account of something
on account of something phrase formal <----- No line break
because of something <----- No ":" character to start the definition
|He doesn't drink alcohol on account of his poor health.
|Organizers were forced to cancel the event on account of the extremely hot weather.
|She was chosen as commencement speaker on account of the fact that she was an alumna of the school.
|Dinner was somewhat delayed on account of David's rather tardy arrival.

**Comment by Alvinceleste2** [comment]
Another little thing. Some verbs or words have particularly strange ways of be printed. For example:

$ camb account for <--- Here the line break is OK.

account for something verb [ T + obj + noun/adj  ]
formal               <---------- Buttt this line should not appear here. In other word searches it is printed just above this one. 
uk |əˈkaʊnt| us |əˈkaʊnt|
: to form the total of something
|Students account for the vast majority of our customers.

**Comment by Alvinceleste2** [comment]
Sorry, but my program relies on such this aspects to work properly. As everything is going to be automatized, everything must follow some guidelines and coherence. I wish you could fix it.

**Comment by mhwgoo** [comment]
hi, have a look at the new version v3.13.8

**Comment by Alvinceleste2** [comment]
I think there is something wrong...

```shell
$ camb brush up
Traceback (most recent call last):
  File "/home/alvinceleste/.local/bin/camb", line 8, in <module>
    sys.exit(run_on_term())
             ^^^^^^^^^^^^^
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/main.py", line 35, in run_on_term
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/main.py", line 16, in main
    await search_word(args)
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/args.py", line 255, in search_word
    await asyncio.gather(*tasks)
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/camb.py", line 36, in search_cambridge
    await cache_run(res_url)
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/camb.py", line 50, in cache_run
    parse_dict_head(block)
  File "/home/alvinceleste/.local/share/pipx/venvs/cambridge/lib/python3.12/site-packages/cambridge/camb.py", line 188, in parse_dict_head
    next_sibling = dgram.find_next_sibling()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_next_sibling'
``` 

I reckon it happens particularly with phrasal verbs maybe

**Comment by mhwgoo** [comment]
sorry, it was introduced by the last update. I've fixed it. Please update to v3.13.9

**Comment by Alvinceleste2** [comment]
Thanks! It seems to be ok now.
